apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: argocd-apps
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Hello from Development</title>
    </head>
    <body>
      <h1>Deployed to Development at Friday, 26 June 2026 3:31:34 PM</h1>
      <p>Release 0.0.10</p>
    </body>
    </html>
